from pylab import *
nx=  145; ny=32; npm=  12
v1=np.zeros([ny,nx])
v2=np.zeros([ny,nx])
#
s11=np.zeros([ny,nx])
s22=np.zeros([ny,nx])
s12=np.zeros([ny,nx])
#
m11=np.zeros([ny,nx])
m22=np.zeros([ny,nx])
m12=np.zeros([ny,nx])
#
mm11=np.zeros([ny,nx])
mm22=np.zeros([ny,nx])
mm12=np.zeros([ny,nx])
#
mu=np.zeros([ny,nx])
muu=np.zeros([ny,nx])
lam=np.zeros([ny,nx])
diss=1e3*np.ones([ny,nx])
rho=np.zeros([ny,nx])
ro1=np.zeros([ny,nx])
ro2=np.zeros([ny,nx])
peak_12=np.zeros(nx)
strini=np.zeros(nx)
rdis=np.zeros(nx)
slip=np.zeros(nx)
broken=np.zeros(nx)
itim=np.zeros(nx)
fault=np.zeros(ny)
